import { StyleSheet } from 'react-native';
import { Colors, Typography, Spacing, Fontsizes } from '../../styles/stylesIndex';

const getMemberStyles = (width, height) => StyleSheet.create({
    membersContainer: {
        ...Typography.sf,
        backgroundColor: Colors.missionInput,
        paddingVertical: Spacing.input,
        borderRadius: Spacing.input,
        marginTop: height * 0.02,
        paddingHorizontal: width * 0.02,
        minHeight: height * 0.06,
    },
    membersScrollView: {
        flexGrow: 0,
    },
    membersScrollContent: {
        alignItems: 'center',
        paddingVertical: height * 0.002,
    },
    memberItem: {
        marginRight: width * 0.02,
        alignItems: 'center',
    },
    memberCircle: {
        minWidth: width * 0.12,
        paddingHorizontal: width * 0.02,
        height: height * 0.035,
        borderRadius: height * 0.0175,
        justifyContent: 'center',
        alignItems: 'center',
        elevation: 2,
        shadowColor: '#000',
        shadowOffset: {
            width: 0,
            height: 1,
        },
        shadowOpacity: 0.22,
        shadowRadius: 2.22,
    },
    memberText: {
        ...Typography.bamin1,
        fontSize: Fontsizes.md,
        color: '#333',
        textAlign: 'center',
        opacity: 0.7,
    },
    addButton: {
        alignItems: 'center',
    },
    addButtonCircle: {
        minWidth: width * 0.12,
        paddingHorizontal: width * 0.03,
        height: height * 0.035,
        borderRadius: height * 0.0175,
        backgroundColor: '#E8E8E8',
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 2,
        borderColor: '#CCC',
        borderStyle: 'dashed',
    },
    addButtonText: {
        ...Typography.bamin1,
        fontSize: Fontsizes.md,
        color: '#999',
    },
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        justifyContent: 'center',
        alignItems: 'center',
        paddingHorizontal: width * 0.1,
        paddingVertical: height * 0.1,
    },
    modalContainer: {
        backgroundColor: 'white',
        borderRadius: 20,
        padding: width * 0.06,
        width: '100%',
        maxWidth: width * 0.8,
        elevation: 5,
        shadowColor: '#000',
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        alignSelf: 'center',
        marginVertical: 'auto',
    },
    modalTitle: {
        ...Typography.bamin1,
        fontSize: Fontsizes.mdm,
        textAlign: 'center',
        marginBottom: height * 0.02,
        color: '#333',
    },
    modalInput: {
        ...Typography.bamin2,
        borderWidth: 1,
        borderColor: '#DDD',
        borderRadius: 10,
        padding: width * 0.04,
        fontSize: Fontsizes.sm,
        marginBottom: height * 0.02,
        textAlign: 'center',
        minHeight: height * 0.05,
    },
    modalButtonContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginTop: height * 0.01, // 위쪽 여백 줄임
    },
    modalCancelButton: {
        flex: 1,
        backgroundColor: '#F0F0F0',
        borderRadius: 10,
        paddingVertical: height * 0.015,
        paddingHorizontal: width * 0.03,
        marginRight: width * 0.02,
        alignItems: 'center',
        minHeight: height * 0.045,
        justifyContent: 'center',
    },
    modalSaveButton: {
        flex: 1,
        backgroundColor: '#007AFF',
        borderRadius: 10,
        paddingVertical: height * 0.015,
        paddingHorizontal: width * 0.03,
        marginLeft: width * 0.02,
        alignItems: 'center',
        minHeight: height * 0.045,
        justifyContent: 'center',
    },
    modalCancelText: {
        ...Typography.bamin1,
        fontSize: Fontsizes.sm,
        color: '#666',
    },
    modalSaveText: {
        ...Typography.bamin1,
        fontSize: Fontsizes.sm,
        color: 'white',
    },
});

export default getMemberStyles;
