import { Colors, Typography, Spacing, Fontsizes } from '../../styles/stylesIndex';
import { StyleSheet, Dimensions } from 'react-native';

const { width, height } = Dimensions.get('window');

const MissionPostScreenStyles = StyleSheet.create({
    safeArea: {
        flex: 1,
    },
    backgroundStyle: {
        backgroundColor: Colors.basic,
        flex: 1,
    },
    backArrow: {
        width: width * 0.12,
        height: width * 0.12,
        position: 'absolute',
        top: height * 0.03,
        left: width * 0.03,
    },
    touchBackArrow: {
        position: 'absolute',
        top: height * 0.03,
        left: width * 0.03,
        width: width * 0.12,
        height: width * 0.12,
        zIndex: 10,
    },
    missionImageWrapper: {
        width: width * 1.0,
        height: height * 0.4,
        backgroundColor: Colors.missions,
        alignItems: 'center',
        justifyContent: 'center',
    },
    uploadedImage: {
        width: '100%',
        height: '100%',
    },
    plusIcon: {
        width: width * 0.2,
        height: width * 0.2,
        opacity: 0.7,
    },
    pencilIconWrapper: {
        position: 'absolute',
        width: width * 0.1,
        height: width * 0.1,
        borderRadius: Spacing.md,
        bottom: width * 0.05,
        right: width * 0.05,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    pencilIcon: {
        width: width * 0.06,
        height: width * 0.06,
        tintColor: 'white',
    },
    missionInfo: {
        flex: 1,
    },
    titleInput: {
        ...Typography.bamin2,
        marginTop: height * 0.02,
        backgroundColor: Colors.inputtext,
        width: width * 0.9,
        height: height * 0.08,
        borderRadius: Spacing.lg,
        alignSelf: 'center',
        paddingLeft: Spacing.sm,
        paddingRight: Spacing.sm,
        fontSize: Fontsizes.mm,
        color: Colors.white,
        textAlignVertical: 'center',
        paddingTop: 0,
        paddingBottom: 0,
    },
    tagInput: {
        ...Typography.bamin2,
        marginTop: height * 0.02,
        backgroundColor: Colors.inputtext,
        width: width * 0.6,
        height: height * 0.06,
        borderRadius: Spacing.lg,
        paddingLeft: Spacing.sm,
        paddingRight: Spacing.sm,
        fontSize: Fontsizes.md,
        color: Colors.white,
        marginLeft: width * 0.05,
        textAlignVertical: 'center',
        paddingTop: 0,
        paddingBottom: 0,
    },
    locationInput: {
        ...Typography.bamin2,
        marginTop: height * 0.02,
        backgroundColor: Colors.inputtext,
        width: width * 0.5,
        height: height * 0.06,
        borderRadius: Spacing.lg,
        paddingLeft: Spacing.sm,
        paddingRight: Spacing.sm,
        fontSize: Fontsizes.md,
        color: Colors.white,
        marginLeft: width * 0.05,
        textAlignVertical: 'center',
        paddingTop: 0,
        paddingBottom: 0,
    },
    plusIconForComments: {
        width: width * 0.1,
        height: width * 0.1,
        opacity: 0.7,
        alignSelf: 'center',
        justifyContent: 'center',
        marginTop: height * 0.02,
        marginBottom: height * 0.02,
    },
    commonButton: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        padding: '5%',
        paddingBottom: height * 0.03,
        backgroundColor: Colors.basic,
    },
    scroll: {
        flex: 1,
    },
    scrollContent: {
        flexGrow: 1,
        paddingBottom: height * 0.15,
    },
    commentWrapper: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
        marginHorizontal: width * 0.05,
        marginTop: height * 0.02,
        marginLeft: width * 0.1,
    },
    deleteButtonWrapper: {
        right: width * 0.08,
        top: height * 0.08,
    },
    deleteButton: {
        ...Typography.bamin1,
        color: Colors.red,
        fontSize: Fontsizes.sm,
    },
});

export default MissionPostScreenStyles;
